gem 'minitest', '~> 5.2'
require 'minitest/autorun'
require 'minitest/pride'
require_relative '../lib/game'
require_relative '../lib/guess'
require_relative '../lib/timeclock'
require_relative '../lib/sequence_generator'
require_relative '../lib/sequence'
require_relative '../lib/sequence_matcher'
require_relative '../lib/printer'
require_relative '../lib/cli'
